from enum import auto
from .auto_name import AutoName

class ChatEventAction(AutoName):
    DESCRIPTION_CHANGED = auto()
    HISTORY_TTL_CHANGED = auto()
    LINKED_CHAT_CHANGED = auto()
    PHOTO_CHANGED = auto()
    TITLE_CHANGED = auto()
    USERNAME_CHANGED = auto()
    CHAT_PERMISSIONS_CHANGED = auto()
    MESSAGE_DELETED = auto()
    MESSAGE_EDITED = auto()
    INVITE_LINK_EDITED = auto()
    INVITE_LINK_REVOKED = auto()
    INVITE_LINK_DELETED = auto()
    MEMBER_INVITED = auto()
    MEMBER_JOINED = auto()
    MEMBER_LEFT = auto()
    ADMINISTRATOR_PRIVILEGES_CHANGED = auto()
    MEMBER_PERMISSIONS_CHANGED = auto()
    POLL_STOPPED = auto()
    INVITES_ENABLED = auto()
    HISTORY_HIDDEN = auto()
    SIGNATURES_ENABLED = auto()
    SLOW_MODE_CHANGED = auto()
    MESSAGE_PINNED = auto()
    MESSAGE_UNPINNED = auto()
    CREATED_FORUM_TOPIC = auto()
    EDITED_FORUM_TOPIC = auto()
    DELETED_FORUM_TOPIC = auto()
    UNKNOWN = auto()
