# # # # # # # # # # # # # # # # # # # # # # # #
#               !!! WARNING !!!               #
#          This is a generated file!          #
# All changes made in this file will be lost! #
# # # # # # # # # # # # # # # # # # # # # # # #

from enum import Enum, auto


class ChatAdminsWithInvites(Enum):
    """Info about chat invites generated by admins."""

    CHAT_ADMINS_WITH_INVITES = auto()
