# # # # # # # # # # # # # # # # # # # # # # # #
#               !!! WARNING !!!               #
#          This is a generated file!          #
# All changes made in this file will be lost! #
# # # # # # # # # # # # # # # # # # # # # # # #

from enum import Enum, auto


class HistoryImportParsed(Enum):
    """Contains information about a chat export file, generated by a foreign chat app."""

    HISTORY_IMPORT_PARSED = auto()
