# # # # # # # # # # # # # # # # # # # # # # # #
#               !!! WARNING !!!               #
#          This is a generated file!          #
# All changes made in this file will be lost! #
# # # # # # # # # # # # # # # # # # # # # # # #

from enum import Enum, auto


class ChannelAdminLogEventAction(Enum):
    """Channel admin log event"""

    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_ABOUT = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_AVAILABLE_REACTIONS = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_EMOJI_STATUS = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_EMOJI_STICKER_SET = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_HISTORY_TTL = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_LINKED_CHAT = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_LOCATION = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_PEER_COLOR = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_PHOTO = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_PROFILE_PEER_COLOR = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_STICKER_SET = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_THEME = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_TITLE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_USERNAME = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_USERNAMES = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CHANGE_WALLPAPER = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_CREATE_TOPIC = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_DEFAULT_BANNED_RIGHTS = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_DELETE_MESSAGE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_DELETE_TOPIC = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_DISCARD_GROUP_CALL = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_EDIT_MESSAGE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_EDIT_TOPIC = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_EXPORTED_INVITE_DELETE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_EXPORTED_INVITE_EDIT = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_EXPORTED_INVITE_REVOKE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_INVITE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_JOIN = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_JOIN_BY_INVITE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_JOIN_BY_REQUEST = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_LEAVE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_MUTE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_SUB_EXTEND = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_TOGGLE_ADMIN = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_TOGGLE_BAN = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_UNMUTE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PARTICIPANT_VOLUME = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_PIN_TOPIC = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_SEND_MESSAGE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_START_GROUP_CALL = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_STOP_POLL = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_ANTI_SPAM = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_AUTOTRANSLATION = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_FORUM = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_GROUP_CALL_SETTING = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_INVITES = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_NO_FORWARDS = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_PRE_HISTORY_HIDDEN = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_SIGNATURE_PROFILES = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_SIGNATURES = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_TOGGLE_SLOW_MODE = auto()
    CHANNEL_ADMIN_LOG_EVENT_ACTION_UPDATE_PINNED = auto()
