name: Auto Tag and Upload Python Package

on:
  push:
    branches:
      - test

jobs:
  tag_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Publish Python Package
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          hatch build
          hatch publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
