name: Rye test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4

      - name: Pin python-version 3.12
        run: rye pin 3.12

      - name: Install dependencies
        run: rye sync

      - name: Generate API
        run: rye run api

      - name: Run tests
        run: rye run python -m pytest
