name: Check style

on: 
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      id: setup-rye
      with:
        enable-cache: true

    - name: Install dependencies
      if: steps.setup-rye.outputs.cache-hit != 'true'
      run: rye sync

    - name: Format the code
      run: |
        rye run ruff format .
        git add .

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit."
        else
          git commit -m "Auto-format code using ruff [skip actions]"
          git push origin ${{ github.ref }}
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
