name: Auto Tag Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version from File
        id: version
        run: echo "::set-output name=version::$(grep -E '__version__ = ".*"' pyrogram/__init__.py | cut -d\" -f2)"

      - name: Check Existing Release
        id: check_release
        run: |
          TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ steps.version.outputs.version }})
          if [[ "$TAG_EXISTS" -eq 200 ]]; then
            echo "Release with tag ${{ steps.version.outputs.version }} already exists."
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV  # Set environment variable
          fi

      - name: Create Release
        if: env.RELEASE_EXISTS != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Release ${{ steps.version.outputs.version }}
