name: Auto Tag Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Version from File
        id: version
        run: |
          VERSION=$(grep -E '__version__ = ".*"' pyrogram/__init__.py | cut -d\" -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check Existing Release
        id: check_release
        run: |
          TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/tags/${{ env.VERSION }})
          if [[ "$TAG_EXISTS" -eq 200 ]]; then
            echo "Release with tag ${{ env.VERSION }} already exists."
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV  # Set environment variable
          fi

      - name: Create Release
        if: env.RELEASE_EXISTS != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GX_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: Release ${{ env.VERSION }}
