name: Auto Tag Workflow

on:
  push:
    branches:
      - main
      - dev

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version from File
        id: version
        run: echo "::set-output name=version::$(grep -oP '__version__ = "\K[^"]+' pyrogram/__init__.py)"

      - name: Tag Commit
        run: git tag ${{ steps.version.outputs.version }} || echo "Tag already exists, skipping."

      - name: Push Tag
        if: success()
        run: git push origin ${{ steps.version.outputs.version }}